

THIS_MAKEFILE = $(CURDIR)/$(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))
HERE = $(dir $(THIS_MAKEFILE))

all: buildcmx


include $(HERE)coq-src/Makefile

buildcmx: $(LINKCMX) $(LIBCOQRUN)
	echo done.

clean:
	cd $(HERE)coq-src
	rm `find -E . -regex '.*\.cmxa?$' -or -name '*.[ao]'`
